"""Unit tests for ``ContextBuilder`` Handover Brief resolution (task09).

The brief resolution contract is described in
``temp/plans/triage-story-point-agent.md`` §6.6 and in
``worklog/claude/triage-agent/tasks/task09.md``.

Two paths are exercised here:

1. **Primary** — inline brief from
   ``current.input_payload.handoff.brief_markdown`` (sibling-impl-execute
   stores the brief inline).
2. **Fallback** — when the inline brief is missing, the optional
   ``brief_resolver`` callback is invoked with ``handoff.from_task_id`` and
   may return a brief loaded from the originating task (typically
   ``triage.result_payload.metadata["handover_brief"]``).

Lineage / ``execute_task.result_payload`` is intentionally **not** consulted
— see the docstring of ``ContextBuilder._resolve_handover_brief`` for the
rationale.
"""

from __future__ import annotations

import pytest

from backend.db import build_engine, build_session_factory, session_scope
from backend.models import Base
from backend.repositories.task_repository import TaskCreateParams, TaskRepository
from backend.services.context_builder import ContextBuilder
from backend.task_constants import TaskType

_INLINE_BRIEF = (
    "## Agent Handover Brief\n"
    "**Assigned Story Points:** 2\n"
    "**Generated by:** AI Triage Gatekeeper\n"
    "\n"
    "### 1. Intent\n"
    "- inline brief body\n"
)

_FALLBACK_BRIEF = (
    "## Agent Handover Brief\n"
    "**Assigned Story Points:** 2\n"
    "**Generated by:** AI Triage Gatekeeper\n"
    "\n"
    "### 1. Intent\n"
    "- fallback brief body\n"
)


@pytest.fixture
def session_factory(tmp_path):
    engine = build_engine(f"sqlite+pysqlite:///{tmp_path / 'app.db'}")
    Base.metadata.create_all(engine)
    return build_session_factory(engine)


def test_handover_brief_primary_from_input_payload(session_factory) -> None:
    """When ``handoff.brief_markdown`` is present inline — return it directly."""

    with session_scope(session_factory=session_factory) as session:
        repository = TaskRepository(session)
        fetch_task = repository.create_task(
            TaskCreateParams(
                task_type=TaskType.FETCH,
                context={"title": "Tracker task"},
            )
        )
        impl_execute_task = repository.create_task(
            TaskCreateParams(
                task_type=TaskType.EXECUTE,
                parent_id=fetch_task.id,
                context={"title": "Implementation execute"},
                input_payload={
                    "action": "implementation",
                    "instructions": "Implement the change.",
                    "handoff": {
                        "from_task_id": 4242,
                        "from_role": "triage",
                        "brief_markdown": _INLINE_BRIEF,
                    },
                },
            )
        )

        effective = ContextBuilder().build_for_task(
            task=impl_execute_task,
            task_chain=repository.load_task_chain(fetch_task.root_id),
            brief_resolver=None,
        )

    assert effective.handover_brief == _INLINE_BRIEF


def test_handover_brief_fallback_when_inline_missing(session_factory) -> None:
    """When the inline brief is missing — invoke ``brief_resolver(from_task_id)``."""

    captured_ids: list[int] = []

    def resolver(from_task_id: int) -> str | None:
        captured_ids.append(from_task_id)
        return _FALLBACK_BRIEF if from_task_id == 42 else None

    with session_scope(session_factory=session_factory) as session:
        repository = TaskRepository(session)
        fetch_task = repository.create_task(
            TaskCreateParams(
                task_type=TaskType.FETCH,
                context={"title": "Tracker task"},
            )
        )
        impl_execute_task = repository.create_task(
            TaskCreateParams(
                task_type=TaskType.EXECUTE,
                parent_id=fetch_task.id,
                context={"title": "Implementation execute"},
                input_payload={
                    "action": "implementation",
                    "instructions": "Implement the change.",
                    "handoff": {
                        "from_task_id": 42,
                        "from_role": "triage",
                        "brief_markdown": None,
                    },
                },
            )
        )

        effective = ContextBuilder().build_for_task(
            task=impl_execute_task,
            task_chain=repository.load_task_chain(fetch_task.root_id),
            brief_resolver=resolver,
        )

    assert effective.handover_brief == _FALLBACK_BRIEF
    assert captured_ids == [42]


def test_handover_brief_none_when_no_handoff_or_resolver(session_factory) -> None:
    """No ``handoff`` payload and no resolver → ``handover_brief`` is ``None``."""

    with session_scope(session_factory=session_factory) as session:
        repository = TaskRepository(session)
        fetch_task = repository.create_task(
            TaskCreateParams(
                task_type=TaskType.FETCH,
                context={"title": "Tracker task"},
            )
        )
        impl_execute_task = repository.create_task(
            TaskCreateParams(
                task_type=TaskType.EXECUTE,
                parent_id=fetch_task.id,
                context={"title": "Implementation execute"},
                input_payload={
                    "action": "implementation",
                    "instructions": "Implement the change without handoff.",
                },
            )
        )

        effective = ContextBuilder().build_for_task(
            task=impl_execute_task,
            task_chain=repository.load_task_chain(fetch_task.root_id),
            brief_resolver=None,
        )

    assert effective.handover_brief is None


def test_handover_brief_none_when_resolver_returns_none(session_factory) -> None:
    """Inline brief missing and resolver returns ``None`` → no brief."""

    def resolver(_from_task_id: int) -> str | None:
        return None

    with session_scope(session_factory=session_factory) as session:
        repository = TaskRepository(session)
        fetch_task = repository.create_task(
            TaskCreateParams(
                task_type=TaskType.FETCH,
                context={"title": "Tracker task"},
            )
        )
        impl_execute_task = repository.create_task(
            TaskCreateParams(
                task_type=TaskType.EXECUTE,
                parent_id=fetch_task.id,
                context={"title": "Implementation execute"},
                input_payload={
                    "action": "implementation",
                    "instructions": "Implement the change.",
                    "handoff": {
                        "from_task_id": 42,
                        "from_role": "triage",
                        "brief_markdown": None,
                    },
                },
            )
        )

        effective = ContextBuilder().build_for_task(
            task=impl_execute_task,
            task_chain=repository.load_task_chain(fetch_task.root_id),
            brief_resolver=resolver,
        )

    assert effective.handover_brief is None
