"""Unit tests for ``backend.services.triage_parser``.

The triage agent stdout contract is defined in ``prompts/agents/triage.md``.
These tests validate the parser deterministically by hand-building the
``<triage_result>`` / ``<markdown>`` envelope — no live LLM is involved.
"""

from __future__ import annotations

import pytest

from backend.services.triage_parser import (
    TriageDecision,
    TriageOutputError,
    parse_triage_output,
)

# ---------------------------------------------------------------------------
# Builders for synthetic stdout
# ---------------------------------------------------------------------------


_HANDOVER_BRIEF_BODY = """## Agent Handover Brief
**Assigned Story Points:** {sp}
**Generated by:** AI Triage Gatekeeper

### 1. Intent (Бизнес-намерение)
- **Цель:** добавить заголовок X-Trace-Id.
- **Ожидаемое состояние:** middleware пишет id во все ответы.

### 2. Execution Design (Дизайн исполнения)
1. Реализовать middleware.
2. Подключить в фабрике приложения.

### 3. Architectural Constraints & Policies (Архитектурные ограничения)
- **ЗАПРЕЩЕНО:** трогать схемы БД.
- **ОБЯЗАТЕЛЬНО:** покрыть unit-тестом.

### 4. Context & Information Dependencies (Контекст и зависимости)
- src/backend/app.py
- src/backend/middleware/__init__.py

### 5. Edge Cases & Procedural Memory (Граничные случаи)
- Запрос без заголовка X-Trace-Id.
- Конкурентные запросы — id должен быть уникальным.

### 6. Acceptance Signals (Сигналы приемки)
- [ ] middleware покрыт unit-тестом.
- [ ] заголовок присутствует во всех ответах.
"""


_RFI_BODY = """## RFI
**Диагноз блокировки:** Выявлен дефицит технического контекста.

**Аналитический срез:** Тикет не определяет источник правды для X.

**Необходимые действия (Action Required):**
Пожалуйста, предоставьте следующую информацию:
1. Откуда берётся X?
2. Какой формат ожидается на выходе?

*Задача заблокирована до получения ответов.*
"""


_DECOMPOSITION_BODY = """## Decomposition
**Диагноз блокировки:** Задача затрагивает слишком много слоёв.

**Аналитический срез:** Эпик: API + миграция БД + фронтенд.

**Сгенерированный план декомпозиции:**
- [ ] Подзадача 1: миграция (SP ≤ 3)
- [ ] Подзадача 2: API endpoint (SP ≤ 3)
- [ ] Подзадача 3: интеграция фронтенда (SP ≤ 3)

**Необходимые действия:** Пожалуйста, утвердите данный план декомпозиции.
"""


_NEEDS_DESIGN_BODY = """## Needs System Design
**Диагноз блокировки:** Критическое нарушение «Definition of Ready for AI».

**Аналитический срез:** Не определены контракты между сервисами и модель данных.

**Необходимые действия:** Задача переведена в статус `Needs System Design`.
"""


def _envelope(
    *,
    story_points: int | str,
    task_kind: str,
    outcome: str,
    markdown_body: str,
) -> str:
    """Render a synthetic triage stdout matching the prompt contract."""

    return (
        "<triage_result>\n"
        f"story_points: {story_points}\n"
        f"task_kind: {task_kind}\n"
        f"outcome: {outcome}\n"
        "</triage_result>\n"
        "<markdown>\n"
        f"{markdown_body}"
        "</markdown>\n"
    )


# ---------------------------------------------------------------------------
# Happy path — one test per allowed Story Point
# ---------------------------------------------------------------------------


def test_parse_sp1_routed_handover_brief() -> None:
    raw = _envelope(
        story_points=1,
        task_kind="implementation",
        outcome="routed",
        markdown_body=_HANDOVER_BRIEF_BODY.format(sp=1),
    )

    decision = parse_triage_output(raw)

    assert isinstance(decision, TriageDecision)
    assert decision.story_points == 1
    assert decision.task_kind == "implementation"
    assert decision.outcome == "routed"
    assert decision.brief_markdown is not None
    assert decision.brief_markdown.startswith("## Agent Handover Brief")
    assert decision.comment_markdown is None
    assert decision.raw_output == raw


def test_parse_sp2_routed_handover_brief() -> None:
    raw = _envelope(
        story_points=2,
        task_kind="implementation",
        outcome="routed",
        markdown_body=_HANDOVER_BRIEF_BODY.format(sp=2),
    )

    decision = parse_triage_output(raw)

    assert decision.story_points == 2
    assert decision.task_kind == "implementation"
    assert decision.outcome == "routed"
    assert decision.brief_markdown is not None
    assert decision.brief_markdown.startswith("## Agent Handover Brief")
    assert decision.comment_markdown is None


def test_parse_sp3_routed_handover_brief() -> None:
    raw = _envelope(
        story_points=3,
        task_kind="implementation",
        outcome="routed",
        markdown_body=_HANDOVER_BRIEF_BODY.format(sp=3),
    )

    decision = parse_triage_output(raw)

    assert decision.story_points == 3
    assert decision.task_kind == "implementation"
    assert decision.outcome == "routed"
    assert decision.brief_markdown is not None
    assert decision.brief_markdown.startswith("## Agent Handover Brief")
    assert decision.comment_markdown is None


def test_parse_sp5_needs_clarification_rfi() -> None:
    raw = _envelope(
        story_points=5,
        task_kind="clarification",
        outcome="needs_clarification",
        markdown_body=_RFI_BODY,
    )

    decision = parse_triage_output(raw)

    assert decision.story_points == 5
    assert decision.task_kind == "clarification"
    assert decision.outcome == "needs_clarification"
    assert decision.brief_markdown is None
    assert decision.comment_markdown is not None
    assert decision.comment_markdown.startswith("## RFI")


def test_parse_sp8_blocked_decomposition() -> None:
    raw = _envelope(
        story_points=8,
        task_kind="rejected",
        outcome="blocked",
        markdown_body=_DECOMPOSITION_BODY,
    )

    decision = parse_triage_output(raw)

    assert decision.story_points == 8
    assert decision.task_kind == "rejected"
    assert decision.outcome == "blocked"
    assert decision.brief_markdown is None
    assert decision.comment_markdown is not None
    assert decision.comment_markdown.startswith("## Decomposition")


def test_parse_sp13_blocked_system_design() -> None:
    raw = _envelope(
        story_points=13,
        task_kind="rejected",
        outcome="blocked",
        markdown_body=_NEEDS_DESIGN_BODY,
    )

    decision = parse_triage_output(raw)

    assert decision.story_points == 13
    assert decision.task_kind == "rejected"
    assert decision.outcome == "blocked"
    assert decision.brief_markdown is None
    assert decision.comment_markdown is not None
    assert decision.comment_markdown.startswith("## Needs System Design")


# ---------------------------------------------------------------------------
# Error cases — required by acceptance criteria
# ---------------------------------------------------------------------------


def test_parse_raises_when_no_triage_result_block() -> None:
    raw = "<markdown>\n## Agent Handover Brief\nbody\n</markdown>\n"

    with pytest.raises(TriageOutputError) as excinfo:
        parse_triage_output(raw)

    assert "exactly one" in str(excinfo.value)


def test_parse_raises_when_two_triage_result_blocks() -> None:
    block_one = (
        "<triage_result>\n"
        "story_points: 1\n"
        "task_kind: implementation\n"
        "outcome: routed\n"
        "</triage_result>\n"
    )
    block_two = (
        "<triage_result>\n"
        "story_points: 2\n"
        "task_kind: implementation\n"
        "outcome: routed\n"
        "</triage_result>\n"
    )
    raw = (
        block_one
        + block_two
        + "<markdown>\n"
        + _HANDOVER_BRIEF_BODY.format(sp=1)
        + "</markdown>\n"
    )

    with pytest.raises(TriageOutputError) as excinfo:
        parse_triage_output(raw)

    assert "exactly one" in str(excinfo.value)


def test_parse_raises_when_invalid_story_points() -> None:
    raw = _envelope(
        story_points=4,
        task_kind="implementation",
        outcome="routed",
        markdown_body=_HANDOVER_BRIEF_BODY.format(sp=4),
    )

    with pytest.raises(TriageOutputError) as excinfo:
        parse_triage_output(raw)

    assert "story_points" in str(excinfo.value)


def test_parse_raises_when_outcome_inconsistent_with_sp() -> None:
    raw = _envelope(
        story_points=2,
        task_kind="implementation",
        outcome="blocked",
        markdown_body=_HANDOVER_BRIEF_BODY.format(sp=2),
    )

    with pytest.raises(TriageOutputError) as excinfo:
        parse_triage_output(raw)

    assert "inconsistent" in str(excinfo.value)


def test_parse_raises_when_markdown_heading_mismatched_template() -> None:
    raw = _envelope(
        story_points=2,
        task_kind="implementation",
        outcome="routed",
        markdown_body=_RFI_BODY,
    )

    with pytest.raises(TriageOutputError) as excinfo:
        parse_triage_output(raw)

    assert "heading" in str(excinfo.value)


# ---------------------------------------------------------------------------
# Bonus invariants (recommended by spec)
# ---------------------------------------------------------------------------


def test_parse_raises_when_no_markdown_block() -> None:
    raw = (
        "<triage_result>\n"
        "story_points: 1\n"
        "task_kind: implementation\n"
        "outcome: routed\n"
        "</triage_result>\n"
    )

    with pytest.raises(TriageOutputError) as excinfo:
        parse_triage_output(raw)

    assert "exactly one" in str(excinfo.value)


def test_parse_raises_when_invalid_task_kind() -> None:
    raw = _envelope(
        story_points=1,
        task_kind="implementer",  # typo — not a valid task_kind
        outcome="routed",
        markdown_body=_HANDOVER_BRIEF_BODY.format(sp=1),
    )

    with pytest.raises(TriageOutputError) as excinfo:
        parse_triage_output(raw)

    assert "task_kind" in str(excinfo.value)
