"""Unit tests for ``backend.services.triage_step``.

``TriageStep`` is a pure orchestration node — no DB, no filesystem, no live
LLM. These tests build a minimal :class:`EffectiveTaskContext` over transient
SQLAlchemy ``Task`` instances (no session needed) and feed canned stdout
through a fake :class:`AgentRunnerProtocol` implementation.
"""

from __future__ import annotations

from dataclasses import dataclass

import pytest

from backend.models import Task
from backend.protocols.agent_runner import (
    AgentRunRequest,
    AgentRunResult,
)
from backend.schemas import TaskContext, TaskResultPayload
from backend.services.triage_step import (
    TriageStep,
    TriageStepError,
    TriageStepResult,
)
from backend.task_constants import TaskType
from backend.task_context import EffectiveTaskContext, TaskChainEntry

# ---------------------------------------------------------------------------
# Fixtures and builders
# ---------------------------------------------------------------------------


_TRIAGE_PROMPT_FIXTURE = (
    "ROLE: Triage Gatekeeper. Goal: classify ticket and emit Story Point.\n"
    "<estimation_matrix>1, 2, 3, 5, 8, 13</estimation_matrix>"
)


_HANDOVER_BRIEF_BODY = """## Agent Handover Brief
**Assigned Story Points:** {sp}
**Generated by:** AI Triage Gatekeeper

### 1. Intent (Бизнес-намерение)
- **Цель:** добавить заголовок X-Trace-Id.
- **Ожидаемое состояние:** middleware пишет id во все ответы.

### 2. Execution Design (Дизайн исполнения)
1. Реализовать middleware.
2. Подключить в фабрике приложения.

### 3. Architectural Constraints & Policies (Архитектурные ограничения)
- **ЗАПРЕЩЕНО:** трогать схемы БД.
- **ОБЯЗАТЕЛЬНО:** покрыть unit-тестом.

### 4. Context & Information Dependencies (Контекст и зависимости)
- src/backend/app.py
- src/backend/middleware/__init__.py

### 5. Edge Cases & Procedural Memory (Граничные случаи)
- Запрос без заголовка X-Trace-Id.
- Конкурентные запросы — id должен быть уникальным.

### 6. Acceptance Signals (Сигналы приемки)
- [ ] middleware покрыт unit-тестом.
- [ ] заголовок присутствует во всех ответах.
"""


_RFI_BODY = """## RFI
**Диагноз блокировки:** Выявлен дефицит технического контекста.

**Аналитический срез:** Тикет не определяет источник правды для X.

**Необходимые действия (Action Required):**
Пожалуйста, предоставьте следующую информацию:
1. Откуда берётся X?
2. Какой формат ожидается на выходе?

*Задача заблокирована до получения ответов.*
"""


_DECOMPOSITION_BODY = """## Decomposition
**Диагноз блокировки:** Задача затрагивает слишком много слоёв.

**Аналитический срез:** Эпик: API + миграция БД + фронтенд.

**Сгенерированный план декомпозиции:**
- [ ] Подзадача 1: миграция (SP ≤ 3)
- [ ] Подзадача 2: API endpoint (SP ≤ 3)
- [ ] Подзадача 3: интеграция фронтенда (SP ≤ 3)

**Необходимые действия:** Пожалуйста, утвердите данный план декомпозиции.
"""


_NEEDS_DESIGN_BODY = """## Needs System Design
**Диагноз блокировки:** Критическое нарушение «Definition of Ready for AI».

**Аналитический срез:** Не определены контракты между сервисами и модель данных.

**Необходимые действия:** Задача переведена в статус `Needs System Design`.
"""


def _envelope(
    *,
    story_points: int,
    task_kind: str,
    outcome: str,
    markdown_body: str,
) -> str:
    return (
        "<triage_result>\n"
        f"story_points: {story_points}\n"
        f"task_kind: {task_kind}\n"
        f"outcome: {outcome}\n"
        "</triage_result>\n"
        "<markdown>\n"
        f"{markdown_body}"
        "</markdown>\n"
    )


@dataclass(slots=True)
class _FakeAgentRunner:
    """Minimal :class:`AgentRunnerProtocol` test double."""

    canned_stdout: str
    parsed_stdout: str | None = None
    last_request: AgentRunRequest | None = None

    def run(self, request: AgentRunRequest) -> AgentRunResult:
        self.last_request = request
        return AgentRunResult(
            payload=TaskResultPayload(summary="fake", token_usage=[]),
            raw_stdout=self.canned_stdout,
            raw_stderr="",
            parsed_stdout=self.parsed_stdout,
        )


def _make_chain_entry(
    *,
    task_id: int,
    task_type: TaskType,
    context: TaskContext | None = None,
) -> TaskChainEntry:
    """Build a transient ``TaskChainEntry`` without involving the DB."""

    task = Task(id=task_id, task_type=task_type)
    entry = TaskChainEntry(task=task)
    object.__setattr__(entry, "context", context)
    object.__setattr__(entry, "input_payload", None)
    object.__setattr__(entry, "result_payload", None)
    return entry


def _make_task_context(
    *,
    title: str = "Add X-Trace-Id middleware",
    description: str | None = "Сквозной trace id во всех ответах backend.",
    acceptance_criteria: list[str] | None = None,
    repo_url: str | None = "https://example.test/repo.git",
    repo_ref: str | None = "main",
    workspace_key: str | None = "repo-x",
) -> EffectiveTaskContext:
    """Compose a minimal :class:`EffectiveTaskContext` for triage tests."""

    if acceptance_criteria is None:
        acceptance_criteria = [
            "middleware покрыт unit-тестом",
            "заголовок присутствует во всех ответах",
        ]

    tracker_context = TaskContext(
        title=title,
        description=description,
        acceptance_criteria=acceptance_criteria,
    )

    fetch_entry = _make_chain_entry(
        task_id=1,
        task_type=TaskType.FETCH,
        context=tracker_context,
    )
    execute_entry = _make_chain_entry(
        task_id=2,
        task_type=TaskType.EXECUTE,
        context=tracker_context,
    )

    return EffectiveTaskContext(
        flow_type=TaskType.EXECUTE,
        root_task=fetch_entry,
        current_task=execute_entry,
        lineage=(fetch_entry, execute_entry),
        fetch_task=fetch_entry,
        execute_task=execute_entry,
        deliver_task=None,
        feedback_task=None,
        feedback_history=(),
        repo_url=repo_url,
        repo_ref=repo_ref,
        workspace_key=workspace_key,
        branch_name=None,
        base_branch=None,
        pr_external_id=None,
        pr_url=None,
        instructions=None,
        commit_message_hint=None,
        handover_brief=None,
    )


# ---------------------------------------------------------------------------
# Happy path — SP routed (1 / 3)
# ---------------------------------------------------------------------------


def test_triage_step_sp1_builds_routed_payload() -> None:
    canned = _envelope(
        story_points=1,
        task_kind="implementation",
        outcome="routed",
        markdown_body=_HANDOVER_BRIEF_BODY.format(sp=1),
    )
    runner = _FakeAgentRunner(canned_stdout=canned)
    step = TriageStep(agent_runner=runner, triage_prompt_text=_TRIAGE_PROMPT_FIXTURE)

    result = step.run(
        task_context=_make_task_context(),
        workspace_path="/tmp/workspace/repo-x",
    )

    assert isinstance(result, TriageStepResult)
    payload = result.result_payload
    assert payload.outcome == "routed"
    assert payload.summary.startswith("Triage завершён: SP=1")

    assert payload.classification is not None
    assert payload.classification.task_kind == "implementation"

    assert payload.estimate is not None
    assert payload.estimate.story_points == 1
    assert payload.estimate.complexity == "trivial"
    assert payload.estimate.can_take_in_work is True
    assert payload.estimate.blocking_reasons == []

    assert payload.routing is not None
    assert payload.routing.create_followup_task is True
    assert payload.routing.next_role == "implementation"
    assert payload.routing.next_task_type == "execute"
    assert payload.routing.requires_human_approval is False

    assert payload.delivery is not None
    assert payload.delivery.tracker_status is None
    assert payload.delivery.tracker_estimate == 1
    assert payload.delivery.tracker_labels == ["sp:1", "triage:ready"]
    assert payload.delivery.escalation_kind is None
    assert payload.delivery.comment_body == "Triage SP=1: Brief сохранён, передано в работу."

    handover = payload.metadata.get("handover_brief")
    assert isinstance(handover, str)
    assert handover.startswith("## Agent Handover Brief")

    assert payload.tracker_comment is None


def test_triage_step_sp3_builds_routed_payload_with_medium_complexity() -> None:
    canned = _envelope(
        story_points=3,
        task_kind="implementation",
        outcome="routed",
        markdown_body=_HANDOVER_BRIEF_BODY.format(sp=3),
    )
    runner = _FakeAgentRunner(canned_stdout=canned)
    step = TriageStep(agent_runner=runner, triage_prompt_text=_TRIAGE_PROMPT_FIXTURE)

    result = step.run(
        task_context=_make_task_context(),
        workspace_path="/tmp/workspace/repo-x",
    )

    payload = result.result_payload
    assert payload.outcome == "routed"
    assert payload.estimate is not None
    assert payload.estimate.story_points == 3
    assert payload.estimate.complexity == "medium"
    assert payload.estimate.can_take_in_work is True
    assert payload.delivery is not None
    assert payload.delivery.tracker_labels == ["sp:3", "triage:ready"]
    assert payload.delivery.tracker_estimate == 3
    assert payload.delivery.escalation_kind is None
    assert payload.routing is not None
    assert payload.routing.create_followup_task is True
    handover = payload.metadata.get("handover_brief")
    assert isinstance(handover, str)
    assert handover.startswith("## Agent Handover Brief")


# ---------------------------------------------------------------------------
# Escalations — SP 5 / 8 / 13
# ---------------------------------------------------------------------------


def test_triage_step_sp5_builds_rfi_delivery() -> None:
    canned = _envelope(
        story_points=5,
        task_kind="clarification",
        outcome="needs_clarification",
        markdown_body=_RFI_BODY,
    )
    runner = _FakeAgentRunner(canned_stdout=canned)
    step = TriageStep(agent_runner=runner, triage_prompt_text=_TRIAGE_PROMPT_FIXTURE)

    result = step.run(
        task_context=_make_task_context(),
        workspace_path="/tmp/workspace/repo-x",
    )

    payload = result.result_payload
    assert payload.outcome == "needs_clarification"
    assert payload.classification is not None
    assert payload.classification.task_kind == "clarification"

    assert payload.estimate is not None
    assert payload.estimate.story_points == 5
    assert payload.estimate.complexity == "high"
    assert payload.estimate.can_take_in_work is False
    assert payload.estimate.blocking_reasons == ["information_deficit"]

    assert payload.routing is not None
    assert payload.routing.create_followup_task is False
    assert payload.routing.next_task_type == "deliver"
    assert payload.routing.next_role == "deliver"
    assert payload.routing.requires_human_approval is True

    assert payload.delivery is not None
    assert payload.delivery.tracker_status is None
    assert payload.delivery.escalation_kind == "rfi"
    assert payload.delivery.tracker_labels == ["sp:5", "triage:rfi"]
    assert payload.delivery.tracker_estimate == 5
    assert payload.delivery.comment_body is not None
    assert payload.delivery.comment_body.startswith("## RFI")

    assert payload.tracker_comment == payload.delivery.comment_body
    assert "handover_brief" not in payload.metadata


def test_triage_step_sp8_builds_decomposition_delivery() -> None:
    canned = _envelope(
        story_points=8,
        task_kind="rejected",
        outcome="blocked",
        markdown_body=_DECOMPOSITION_BODY,
    )
    runner = _FakeAgentRunner(canned_stdout=canned)
    step = TriageStep(agent_runner=runner, triage_prompt_text=_TRIAGE_PROMPT_FIXTURE)

    result = step.run(
        task_context=_make_task_context(),
        workspace_path="/tmp/workspace/repo-x",
    )

    payload = result.result_payload
    assert payload.outcome == "blocked"
    assert payload.classification is not None
    assert payload.classification.task_kind == "rejected"
    assert payload.estimate is not None
    assert payload.estimate.story_points == 8
    assert payload.estimate.complexity == "epic"
    assert payload.estimate.blocking_reasons == ["scope_too_large"]
    assert payload.delivery is not None
    assert payload.delivery.escalation_kind == "decomposition"
    assert payload.delivery.tracker_labels == ["sp:8", "triage:split"]
    assert payload.delivery.tracker_status is None
    assert payload.delivery.comment_body is not None
    assert payload.delivery.comment_body.startswith("## Decomposition")
    assert payload.tracker_comment == payload.delivery.comment_body
    assert "handover_brief" not in payload.metadata


def test_triage_step_sp13_builds_system_design_delivery() -> None:
    canned = _envelope(
        story_points=13,
        task_kind="rejected",
        outcome="blocked",
        markdown_body=_NEEDS_DESIGN_BODY,
    )
    runner = _FakeAgentRunner(canned_stdout=canned)
    step = TriageStep(agent_runner=runner, triage_prompt_text=_TRIAGE_PROMPT_FIXTURE)

    result = step.run(
        task_context=_make_task_context(),
        workspace_path="/tmp/workspace/repo-x",
    )

    payload = result.result_payload
    assert payload.outcome == "blocked"
    assert payload.estimate is not None
    assert payload.estimate.story_points == 13
    assert payload.estimate.complexity == "architectural"
    assert payload.estimate.blocking_reasons == ["architectural_ambiguity"]
    assert payload.delivery is not None
    assert payload.delivery.escalation_kind == "system_design"
    assert payload.delivery.tracker_labels == ["sp:13", "triage:block"]
    assert payload.delivery.tracker_status is None
    assert payload.delivery.comment_body is not None
    assert payload.delivery.comment_body.startswith("## Needs System Design")
    assert payload.tracker_comment == payload.delivery.comment_body
    assert "handover_brief" not in payload.metadata


# ---------------------------------------------------------------------------
# Error handling
# ---------------------------------------------------------------------------


def test_triage_step_raises_on_malformed_output() -> None:
    runner = _FakeAgentRunner(canned_stdout="absolutely not the contract")
    step = TriageStep(agent_runner=runner, triage_prompt_text=_TRIAGE_PROMPT_FIXTURE)

    with pytest.raises(TriageStepError) as excinfo:
        step.run(
            task_context=_make_task_context(),
            workspace_path="/tmp/workspace/repo-x",
        )

    assert "triage_output_malformed" in str(excinfo.value)


def test_triage_step_prefers_parsed_stdout_from_cli_text_events() -> None:
    parsed_stdout = _envelope(
        story_points=5,
        task_kind="clarification",
        outcome="needs_clarification",
        markdown_body=_RFI_BODY,
    )
    runner = _FakeAgentRunner(
        canned_stdout=(
            '{"type":"text","part":{"type":"text",'
            '"text":"<triage_result>\\nstory_points: 5"}}'
        ),
        parsed_stdout=parsed_stdout,
    )
    step = TriageStep(agent_runner=runner, triage_prompt_text=_TRIAGE_PROMPT_FIXTURE)

    result = step.run(
        task_context=_make_task_context(),
        workspace_path="/tmp/workspace/repo-x",
    )

    assert result.decision.story_points == 5
    assert result.result_payload.outcome == "needs_clarification"


# ---------------------------------------------------------------------------
# Prompt rendering
# ---------------------------------------------------------------------------


def test_triage_step_prompt_includes_role_and_task_context() -> None:
    runner = _FakeAgentRunner(canned_stdout="")  # not used here
    step = TriageStep(agent_runner=runner, triage_prompt_text=_TRIAGE_PROMPT_FIXTURE)

    available_context = _make_task_context(
        title="Add X-Trace-Id middleware",
        description="Сквозной trace id во всех ответах backend.",
        acceptance_criteria=["middleware покрыт unit-тестом"],
        repo_url="https://example.test/repo.git",
        repo_ref="main",
        workspace_key="repo-x",
    )
    rendered_available = step.build_prompt(task_context=available_context)

    assert "<role>" in rendered_available
    assert "</role>" in rendered_available
    assert "ROLE: Triage Gatekeeper" in rendered_available

    assert "<task_context>" in rendered_available
    assert "title: Add X-Trace-Id middleware" in rendered_available
    assert "description: Сквозной trace id во всех ответах backend." in rendered_available
    assert "- middleware покрыт unit-тестом" in rendered_available

    assert "<repo_signals>" in rendered_available
    assert "repo_url: https://example.test/repo.git" in rendered_available
    assert "repo_available: true" in rendered_available

    assert "<expected_output>" in rendered_available

    missing_context = _make_task_context(
        repo_url=None,
        repo_ref="main",
        workspace_key="repo-x",
    )
    rendered_missing = step.build_prompt(task_context=missing_context)
    assert "repo_available: false" in rendered_missing


def test_triage_step_passes_built_prompt_to_runner() -> None:
    """Critical: the triage prompt must reach the runner via prompt_override.

    Without this, ``CliAgentRunner`` would fall back to its generic
    ``_build_prompt`` and the triage agent would never see the
    ``<role>/<task_context>/<repo_signals>/<expected_output>`` contract.
    """

    canned = _envelope(
        story_points=2,
        task_kind="implementation",
        outcome="routed",
        markdown_body=_HANDOVER_BRIEF_BODY.format(sp=2),
    )
    runner = _FakeAgentRunner(canned_stdout=canned)
    step = TriageStep(agent_runner=runner, triage_prompt_text=_TRIAGE_PROMPT_FIXTURE)

    step.run(
        task_context=_make_task_context(),
        workspace_path="/tmp/workspace/repo-x",
    )

    assert runner.last_request is not None
    prompt = runner.last_request.prompt_override
    assert prompt is not None, "TriageStep.run must set AgentRunRequest.prompt_override"
    assert "<role>" in prompt
    assert "ROLE: Triage Gatekeeper" in prompt  # from _TRIAGE_PROMPT_FIXTURE
    assert "<task_context>" in prompt
    assert "title: Add X-Trace-Id middleware" in prompt
    assert "<repo_signals>" in prompt
    assert "repo_available: true" in prompt
    assert "<expected_output>" in prompt
