"""Tests for ExecuteWorker action-routing → TriageStep dispatch (task06).

These tests cover ``_resolve_execute_action`` + ``_process_triage_execute`` —
the path that turns ``input_payload.action == "triage"`` (or the migration
default for a single-execute cluster) into a ``TriageStep.run`` call instead
of the impl-flow. PR_FEEDBACK regression and FAILED-handling for malformed
output are also exercised here.
"""

from __future__ import annotations

from dataclasses import dataclass, field, replace
from pathlib import Path

from backend.adapters.mock_scm import MockScm
from backend.db import build_engine, build_session_factory, session_scope
from backend.models import Base, Task
from backend.protocols.agent_runner import AgentRunRequest, AgentRunResult
from backend.repositories.task_repository import TaskCreateParams, TaskRepository
from backend.schemas import TaskResultPayload
from backend.settings import Settings, get_settings
from backend.task_constants import TaskStatus, TaskType
from backend.workers.execute_worker import ExecuteWorker
from test_execute_worker import EnsureWorkspaceRecorderMockScm, RecordingAgentRunner

# ---------------------------------------------------------------------------
# Helpers (canned envelopes + fake runner)
# ---------------------------------------------------------------------------


_HANDOVER_BRIEF_BODY = """## Agent Handover Brief
**Assigned Story Points:** 2
**Generated by:** AI Triage Gatekeeper

### 1. Intent
- Цель: добавить middleware.

### 2. Execution Design
1. Реализовать middleware.

### 3. Architectural Constraints
- Покрыть unit-тестом.

### 4. Context
- src/backend/app.py

### 5. Edge Cases
- Конкурентные запросы.

### 6. Acceptance Signals
- [ ] middleware покрыт unit-тестом.
"""


def _envelope(
    *,
    story_points: int,
    task_kind: str,
    outcome: str,
    markdown_body: str,
) -> str:
    return (
        "<triage_result>\n"
        f"story_points: {story_points}\n"
        f"task_kind: {task_kind}\n"
        f"outcome: {outcome}\n"
        "</triage_result>\n"
        "<markdown>\n"
        f"{markdown_body}"
        "</markdown>\n"
    )


@dataclass(slots=True)
class _FakeAgentRunner:
    """Minimal AgentRunnerProtocol double — returns canned stdout."""

    canned_stdout: str
    last_request: AgentRunRequest | None = None
    requests: list[AgentRunRequest] = field(default_factory=list)

    def run(self, request: AgentRunRequest) -> AgentRunResult:
        self.last_request = request
        self.requests.append(request)
        return AgentRunResult(
            payload=TaskResultPayload(summary="fake", token_usage=[]),
            raw_stdout=self.canned_stdout,
            raw_stderr="",
        )


# ---------------------------------------------------------------------------
# Session / Settings fixtures
# ---------------------------------------------------------------------------


def _build_session_factory(tmp_path):
    engine = build_engine(f"sqlite+pysqlite:///{tmp_path / 'app.db'}")
    Base.metadata.create_all(engine)
    return build_session_factory(engine)


def _build_settings(tmp_path: Path) -> Settings:
    """Settings with an isolated workspace_root and prompts_dir under tmp_path.

    The triage prompt body is irrelevant for these tests (TriageStep injects it
    verbatim into the prompt and the fake runner ignores the prompt) — we only
    need ``load_triage_prompt`` to find a non-empty file at
    ``<prompts_dir>/agents/triage.md``.
    """

    prompts_dir = tmp_path / "prompts"
    (prompts_dir / "agents").mkdir(parents=True, exist_ok=True)
    (prompts_dir / "agents" / "triage.md").write_text(
        "ROLE: Triage Gatekeeper. Goal: classify ticket and emit Story Point.",
        encoding="utf-8",
    )
    return replace(
        get_settings(),
        workspace_root=str(tmp_path / "workspaces"),
        prompts_dir=str(prompts_dir),
    )


def _create_fetch(repository: TaskRepository, *, with_repo: bool = True, suffix: str = "1") -> Task:
    if with_repo:
        return repository.create_task(
            TaskCreateParams(
                task_type=TaskType.FETCH,
                tracker_name="mock",
                external_task_id=f"TASK-{suffix}",
                repo_url="https://example.test/repo.git",
                repo_ref="main",
                workspace_key=f"repo-{suffix}",
                context={"title": "Tracker task"},
            )
        )
    return repository.create_task(
        TaskCreateParams(
            task_type=TaskType.FETCH,
            tracker_name="mock",
            external_task_id=f"TASK-{suffix}",
            context={"title": "Tracker task without repo"},
        )
    )


# ---------------------------------------------------------------------------
# Test 1 — explicit action="triage" → TriageStep.run with full DONE flow
# ---------------------------------------------------------------------------


def test_execute_worker_routes_triage_action_through_triage_step(tmp_path) -> None:
    session_factory = _build_session_factory(tmp_path)
    settings = _build_settings(tmp_path)
    fake = _FakeAgentRunner(
        canned_stdout=_envelope(
            story_points=2,
            task_kind="implementation",
            outcome="routed",
            markdown_body=_HANDOVER_BRIEF_BODY,
        )
    )
    worker = ExecuteWorker(
        scm=MockScm(),
        agent_runner=fake,
        session_factory=session_factory,
        settings=settings,
    )

    with session_scope(session_factory=session_factory) as session:
        repository = TaskRepository(session)
        fetch = _create_fetch(repository, suffix="1")
        triage_task = repository.create_task(
            TaskCreateParams(
                task_type=TaskType.EXECUTE,
                parent_id=fetch.id,
                tracker_name="mock",
                external_parent_id="TASK-1",
                repo_url="https://example.test/repo.git",
                repo_ref="main",
                workspace_key="repo-1",
                context={"title": "Triage execute"},
                input_payload={"action": "triage"},
            )
        )
        triage_id = triage_task.id

    report = worker.poll_once()

    assert report.processed_execute_tasks == 1
    assert report.failed_execute_tasks == 0
    assert len(fake.requests) == 1
    request = fake.requests[0]
    assert request.workspace_path == "/tmp/mock-scm/repo-1"
    assert request.metadata["action"] == "triage"

    with session_scope(session_factory=session_factory) as session:
        triage_row = session.get(Task, triage_id)
        assert triage_row is not None
        assert triage_row.status == TaskStatus.DONE
        assert triage_row.branch_name is None
        assert triage_row.pr_external_id is None
        assert triage_row.pr_url is None
        assert triage_row.result_payload is not None
        assert triage_row.result_payload["estimate"]["story_points"] == 2
        assert triage_row.result_payload["delivery"]["tracker_labels"] == ["sp:2", "triage:ready"]
        handover = triage_row.result_payload["metadata"].get("handover_brief")
        assert isinstance(handover, str)
        assert handover.startswith("## Agent Handover Brief")

        deliver = (
            session.query(Task)
            .filter(Task.parent_id == triage_id, Task.task_type == TaskType.DELIVER)
            .first()
        )
        assert deliver is not None
        assert deliver.status == TaskStatus.NEW


# ---------------------------------------------------------------------------
# Test 2 — default for execute without action → impl-flow (legacy preservation)
# ---------------------------------------------------------------------------


def test_execute_worker_defaults_to_implementation_when_action_missing(tmp_path) -> None:
    """Legacy execute-задачи без явного ``action`` обязаны идти по impl-flow.

    До миграции worker всегда уходил в impl-flow: любая уже существующая в
    БД single-execute-задача должна остаться там же, иначе после rollout
    повторно поднятые legacy-задачи внезапно уйдут в triage и не получат
    branch/PR. Триаж назначается **только** через явный
    ``action="triage"`` от ``tracker_intake`` (task08).
    """

    session_factory = _build_session_factory(tmp_path)
    settings = _build_settings(tmp_path)
    agent_runner = RecordingAgentRunner()
    worker = ExecuteWorker(
        scm=MockScm(),
        agent_runner=agent_runner,
        session_factory=session_factory,
        settings=settings,
    )

    with session_scope(session_factory=session_factory) as session:
        repository = TaskRepository(session)
        fetch = _create_fetch(repository, suffix="2")
        execute = repository.create_task(
            TaskCreateParams(
                task_type=TaskType.EXECUTE,
                parent_id=fetch.id,
                tracker_name="mock",
                external_parent_id="TASK-2",
                repo_url="https://example.test/repo.git",
                repo_ref="main",
                workspace_key="repo-2",
                context={"title": "Legacy execute"},
                input_payload={  # no action key — should default to impl-flow
                    "instructions": "Run.",
                    "branch_name": "task2/run",
                    "base_branch": "main",
                },
            )
        )
        execute_id = execute.id

    report = worker.poll_once()

    assert report.processed_execute_tasks == 1
    assert len(agent_runner.requests) == 1

    with session_scope(session_factory=session_factory) as session:
        execute_row = session.get(Task, execute_id)
        assert execute_row is not None
        assert execute_row.status == TaskStatus.DONE
        # impl-flow создаёт branch + PR — это доказывает, что мы НЕ ушли в triage.
        assert execute_row.branch_name == "task2/run"
        assert execute_row.pr_external_id is not None


# ---------------------------------------------------------------------------
# Test 3 — explicit action="triage" wins even when sibling execute exists
# ---------------------------------------------------------------------------


def test_execute_worker_routes_explicit_triage_even_with_sibling_execute(tmp_path) -> None:
    """Sibling-фильтр выпилен: explicit ``action`` всегда выигрывает.

    После Codex-fix `_resolve_execute_action` смотрит **только** на
    `input_payload.action`. Sibling-execute больше не влияет ни в какую
    сторону — это страхует от случая, где человек руками поставил
    `action="triage"` на «не-первую» execute (например, для re-triage
    через task18).
    """

    session_factory = _build_session_factory(tmp_path)
    settings = _build_settings(tmp_path)
    fake = _FakeAgentRunner(
        canned_stdout=_envelope(
            story_points=2,
            task_kind="implementation",
            outcome="routed",
            markdown_body=_HANDOVER_BRIEF_BODY,
        )
    )
    worker = ExecuteWorker(
        scm=MockScm(),
        agent_runner=fake,
        session_factory=session_factory,
        settings=settings,
    )

    with session_scope(session_factory=session_factory) as session:
        repository = TaskRepository(session)
        fetch = _create_fetch(repository, suffix="3")
        # Existing DONE execute — must NOT pull the new triage into impl-flow.
        repository.create_task(
            TaskCreateParams(
                task_type=TaskType.EXECUTE,
                parent_id=fetch.id,
                status=TaskStatus.DONE,
                tracker_name="mock",
                external_parent_id="TASK-3",
                repo_url="https://example.test/repo.git",
                repo_ref="main",
                workspace_key="repo-3",
                context={"title": "Earlier execute"},
                input_payload={"action": "implementation"},
            )
        )
        triage_task = repository.create_task(
            TaskCreateParams(
                task_type=TaskType.EXECUTE,
                parent_id=fetch.id,
                tracker_name="mock",
                external_parent_id="TASK-3",
                repo_url="https://example.test/repo.git",
                repo_ref="main",
                workspace_key="repo-3",
                context={"title": "Re-triage"},
                input_payload={"action": "triage"},
            )
        )
        triage_id = triage_task.id

    report = worker.poll_once()

    assert report.processed_execute_tasks == 1
    assert len(fake.requests) == 1
    assert fake.requests[0].metadata["action"] == "triage"

    with session_scope(session_factory=session_factory) as session:
        triage_row = session.get(Task, triage_id)
        assert triage_row is not None
        assert triage_row.status == TaskStatus.DONE
        assert triage_row.branch_name is None  # triage path — no SCM artifacts
        assert triage_row.result_payload is not None
        assert triage_row.result_payload["estimate"]["story_points"] == 2


# ---------------------------------------------------------------------------
# Test 4 — explicit action="implementation" → impl-flow
# ---------------------------------------------------------------------------


def test_execute_worker_routes_implementation_when_action_explicit(tmp_path) -> None:
    session_factory = _build_session_factory(tmp_path)
    settings = _build_settings(tmp_path)
    agent_runner = RecordingAgentRunner()
    worker = ExecuteWorker(
        scm=MockScm(),
        agent_runner=agent_runner,
        session_factory=session_factory,
        settings=settings,
    )

    with session_scope(session_factory=session_factory) as session:
        repository = TaskRepository(session)
        fetch = _create_fetch(repository, suffix="4")
        execute_task = repository.create_task(
            TaskCreateParams(
                task_type=TaskType.EXECUTE,
                parent_id=fetch.id,
                tracker_name="mock",
                external_parent_id="TASK-4",
                repo_url="https://example.test/repo.git",
                repo_ref="main",
                workspace_key="repo-4",
                context={"title": "Explicit impl"},
                input_payload={
                    "action": "implementation",
                    "instructions": "Run.",
                    "branch_name": "task4/run",
                    "base_branch": "main",
                },
            )
        )
        execute_id = execute_task.id

    report = worker.poll_once()

    assert report.processed_execute_tasks == 1
    assert len(agent_runner.requests) == 1

    with session_scope(session_factory=session_factory) as session:
        execute_row = session.get(Task, execute_id)
        assert execute_row is not None
        assert execute_row.status == TaskStatus.DONE
        assert execute_row.branch_name == "task4/run"
        assert execute_row.pr_external_id is not None


# ---------------------------------------------------------------------------
# Test 5 — TriageStepError → FAILED with raw_stdout preview
# ---------------------------------------------------------------------------


def test_execute_worker_marks_triage_failed_on_malformed_output(tmp_path) -> None:
    session_factory = _build_session_factory(tmp_path)
    settings = _build_settings(tmp_path)
    fake = _FakeAgentRunner(canned_stdout="absolutely not the contract")
    worker = ExecuteWorker(
        scm=MockScm(),
        agent_runner=fake,
        session_factory=session_factory,
        settings=settings,
    )

    with session_scope(session_factory=session_factory) as session:
        repository = TaskRepository(session)
        fetch = _create_fetch(repository, suffix="5")
        triage_task = repository.create_task(
            TaskCreateParams(
                task_type=TaskType.EXECUTE,
                parent_id=fetch.id,
                tracker_name="mock",
                external_parent_id="TASK-5",
                repo_url="https://example.test/repo.git",
                repo_ref="main",
                workspace_key="repo-5",
                context={"title": "Triage execute"},
                input_payload={"action": "triage"},
            )
        )
        triage_id = triage_task.id

    report = worker.poll_once()

    assert report.failed_execute_tasks == 1
    assert report.processed_execute_tasks == 0

    with session_scope(session_factory=session_factory) as session:
        triage_row = session.get(Task, triage_id)
        assert triage_row is not None
        assert triage_row.status == TaskStatus.FAILED
        assert triage_row.error == "triage_output_malformed"
        assert triage_row.result_payload is not None
        assert triage_row.result_payload["summary"] == "Triage agent output malformed."
        preview = triage_row.result_payload["metadata"]["raw_stdout_preview"]
        assert preview == "absolutely not the contract"
        assert len(preview) <= 2000

        deliver = (
            session.query(Task)
            .filter(Task.parent_id == triage_id, Task.task_type == TaskType.DELIVER)
            .first()
        )
        assert deliver is None


# ---------------------------------------------------------------------------
# Test 6 — raw_stdout > 2000 chars → preview truncated to 2000
# ---------------------------------------------------------------------------


def test_execute_worker_truncates_raw_stdout_preview_at_2000_chars(tmp_path) -> None:
    session_factory = _build_session_factory(tmp_path)
    settings = _build_settings(tmp_path)
    fake = _FakeAgentRunner(canned_stdout="X" * 5000)
    worker = ExecuteWorker(
        scm=MockScm(),
        agent_runner=fake,
        session_factory=session_factory,
        settings=settings,
    )

    with session_scope(session_factory=session_factory) as session:
        repository = TaskRepository(session)
        fetch = _create_fetch(repository, suffix="6")
        triage_task = repository.create_task(
            TaskCreateParams(
                task_type=TaskType.EXECUTE,
                parent_id=fetch.id,
                tracker_name="mock",
                external_parent_id="TASK-6",
                repo_url="https://example.test/repo.git",
                repo_ref="main",
                workspace_key="repo-6",
                context={"title": "Triage execute"},
                input_payload={"action": "triage"},
            )
        )
        triage_id = triage_task.id

    worker.poll_once()

    with session_scope(session_factory=session_factory) as session:
        triage_row = session.get(Task, triage_id)
        assert triage_row is not None
        assert triage_row.status == TaskStatus.FAILED
        assert triage_row.result_payload is not None
        preview = triage_row.result_payload["metadata"]["raw_stdout_preview"]
        assert len(preview) == 2000
        assert preview == "X" * 2000


# ---------------------------------------------------------------------------
# Test 7 — no-repo triage cleans tmp dir on success
# ---------------------------------------------------------------------------


def test_execute_worker_cleans_up_triage_tmp_dir_after_run(tmp_path) -> None:
    session_factory = _build_session_factory(tmp_path)
    settings = _build_settings(tmp_path)
    fake = _FakeAgentRunner(
        canned_stdout=_envelope(
            story_points=2,
            task_kind="implementation",
            outcome="routed",
            markdown_body=_HANDOVER_BRIEF_BODY,
        )
    )
    worker = ExecuteWorker(
        scm=MockScm(),
        agent_runner=fake,
        session_factory=session_factory,
        settings=settings,
    )

    with session_scope(session_factory=session_factory) as session:
        repository = TaskRepository(session)
        fetch = _create_fetch(repository, with_repo=False, suffix="7")
        triage_task = repository.create_task(
            TaskCreateParams(
                task_type=TaskType.EXECUTE,
                parent_id=fetch.id,
                tracker_name="mock",
                external_parent_id="TASK-7",
                context={"title": "Triage execute (no repo)"},
                input_payload={"action": "triage"},
            )
        )
        triage_id = triage_task.id

    expected_tmp = Path(settings.workspace_root) / "__triage__" / f"task-{triage_id}"

    worker.poll_once()

    assert not expected_tmp.exists()
    with session_scope(session_factory=session_factory) as session:
        triage_row = session.get(Task, triage_id)
        assert triage_row is not None
        assert triage_row.status == TaskStatus.DONE


# ---------------------------------------------------------------------------
# Test 8 — no-repo triage cleans tmp dir on TriageStepError too
# ---------------------------------------------------------------------------


def test_execute_worker_cleans_up_triage_tmp_dir_after_malformed_output(tmp_path) -> None:
    session_factory = _build_session_factory(tmp_path)
    settings = _build_settings(tmp_path)
    fake = _FakeAgentRunner(canned_stdout="garbage")
    worker = ExecuteWorker(
        scm=MockScm(),
        agent_runner=fake,
        session_factory=session_factory,
        settings=settings,
    )

    with session_scope(session_factory=session_factory) as session:
        repository = TaskRepository(session)
        fetch = _create_fetch(repository, with_repo=False, suffix="8")
        triage_task = repository.create_task(
            TaskCreateParams(
                task_type=TaskType.EXECUTE,
                parent_id=fetch.id,
                tracker_name="mock",
                external_parent_id="TASK-8",
                context={"title": "Triage execute (no repo)"},
                input_payload={"action": "triage"},
            )
        )
        triage_id = triage_task.id

    expected_tmp = Path(settings.workspace_root) / "__triage__" / f"task-{triage_id}"

    worker.poll_once()

    assert not expected_tmp.exists()
    with session_scope(session_factory=session_factory) as session:
        triage_row = session.get(Task, triage_id)
        assert triage_row is not None
        assert triage_row.status == TaskStatus.FAILED


# ---------------------------------------------------------------------------
# Test 9 — triage prompt loaded once and reused across runs
# ---------------------------------------------------------------------------


def test_execute_worker_lazy_loads_triage_prompt_once(tmp_path, monkeypatch) -> None:
    session_factory = _build_session_factory(tmp_path)
    settings = _build_settings(tmp_path)
    fake = _FakeAgentRunner(
        canned_stdout=_envelope(
            story_points=2,
            task_kind="implementation",
            outcome="routed",
            markdown_body=_HANDOVER_BRIEF_BODY,
        )
    )
    worker = ExecuteWorker(
        scm=MockScm(),
        agent_runner=fake,
        session_factory=session_factory,
        settings=settings,
    )

    call_counter = {"count": 0}
    from backend.workers import execute_worker as worker_module

    original_load = worker_module.load_triage_prompt

    def counting_load(prompts_dir):
        call_counter["count"] += 1
        return original_load(prompts_dir)

    monkeypatch.setattr(worker_module, "load_triage_prompt", counting_load)

    with session_scope(session_factory=session_factory) as session:
        repository = TaskRepository(session)
        for idx in range(2):
            fetch = _create_fetch(repository, suffix=f"9-{idx}")
            repository.create_task(
                TaskCreateParams(
                    task_type=TaskType.EXECUTE,
                    parent_id=fetch.id,
                    tracker_name="mock",
                    external_parent_id=f"TASK-9-{idx}",
                    repo_url="https://example.test/repo.git",
                    repo_ref="main",
                    workspace_key=f"repo-9-{idx}",
                    context={"title": "Triage execute"},
                    input_payload={"action": "triage"},
                )
            )

    worker.poll_once()
    worker.poll_once()

    assert worker._triage_prompt_text is not None
    assert call_counter["count"] == 1


# ---------------------------------------------------------------------------
# Test 10 — workspace_path forwarded from PreparedTriageExecution
# ---------------------------------------------------------------------------


def test_execute_worker_triage_passes_workspace_path_to_runner(tmp_path) -> None:
    session_factory = _build_session_factory(tmp_path)
    settings = _build_settings(tmp_path)
    fake = _FakeAgentRunner(
        canned_stdout=_envelope(
            story_points=2,
            task_kind="implementation",
            outcome="routed",
            markdown_body=_HANDOVER_BRIEF_BODY,
        )
    )
    scm = EnsureWorkspaceRecorderMockScm()
    worker = ExecuteWorker(
        scm=scm,
        agent_runner=fake,
        session_factory=session_factory,
        settings=settings,
    )

    with session_scope(session_factory=session_factory) as session:
        repository = TaskRepository(session)
        fetch = _create_fetch(repository, suffix="10")
        repository.create_task(
            TaskCreateParams(
                task_type=TaskType.EXECUTE,
                parent_id=fetch.id,
                tracker_name="mock",
                external_parent_id="TASK-10",
                repo_url="https://example.test/repo.git",
                repo_ref="main",
                workspace_key="repo-10",
                context={"title": "Triage execute"},
                input_payload={"action": "triage"},
            )
        )

    worker.poll_once()

    assert fake.last_request is not None
    # local_path produced by MockScm.ensure_workspace for workspace_key="repo-10".
    assert fake.last_request.workspace_path == "/tmp/mock-scm/repo-10"
    assert len(scm.ensure_workspace_payloads) == 1


# ---------------------------------------------------------------------------
# Test 11 — PR_FEEDBACK ignores the action-router (impl-flow always)
# ---------------------------------------------------------------------------


def test_execute_worker_triage_pr_feedback_is_unaffected(tmp_path) -> None:
    """PR_FEEDBACK never goes through TriageStep, even with action="triage"."""

    session_factory = _build_session_factory(tmp_path)
    settings = _build_settings(tmp_path)
    fake = _FakeAgentRunner(canned_stdout="should never be invoked")
    worker = ExecuteWorker(
        scm=MockScm(),
        agent_runner=fake,
        session_factory=session_factory,
        settings=settings,
    )

    with session_scope(session_factory=session_factory) as session:
        repository = TaskRepository(session)
        fetch = _create_fetch(repository, suffix="11")
        # impl execute already DONE so the feedback task has a sane parent chain.
        execute_task = repository.create_task(
            TaskCreateParams(
                task_type=TaskType.EXECUTE,
                parent_id=fetch.id,
                status=TaskStatus.DONE,
                tracker_name="mock",
                external_parent_id="TASK-11",
                repo_url="https://example.test/repo.git",
                repo_ref="main",
                workspace_key="repo-11",
                branch_name="task11/branch",
                context={"title": "Earlier impl"},
                input_payload={"action": "implementation"},
            )
        )
        feedback_task = repository.create_task(
            TaskCreateParams(
                task_type=TaskType.PR_FEEDBACK,
                parent_id=execute_task.id,
                tracker_name="mock",
                external_parent_id="TASK-11",
                repo_url="https://example.test/repo.git",
                repo_ref="main",
                workspace_key="repo-11",
                branch_name="task11/branch",
                context={"title": "PR feedback"},
                # Intentionally "wrong" action — must NOT divert PR_FEEDBACK to triage.
                input_payload={"action": "triage"},
            )
        )
        feedback_id = feedback_task.id

    report = worker.poll_once()

    # PR_FEEDBACK must not invoke the triage runner — it goes through impl-flow,
    # which fails because there's no existing PR (test 11 alt-assertion in spec).
    assert fake.requests == []
    assert report.failed_pr_feedback_tasks == 1

    with session_scope(session_factory=session_factory) as session:
        feedback_row = session.get(Task, feedback_id)
        assert feedback_row is not None
        assert feedback_row.status == TaskStatus.FAILED
        # impl-flow PR_FEEDBACK error reaches us via _complete_pr_feedback_task
        # ("pr_feedback task requires an existing pull request"). Whatever the
        # exact message, it must NOT be the triage-error string.
        assert feedback_row.error is not None
        assert "triage_output_malformed" not in feedback_row.error
